config/routes.rb
Spree::Core::Engine.routes.draw do
  post 'like_product/:id', to: 'likes#like_product', as: 'like_product'
  delete 'unlike_product/:id', to: 'likes#unlike_product', as: 'unlike_product'
  get '/favourites', to: 'likes#index', as: 'products_favourites'
  namespace :admin do
    get '/products/products_ranking', as: 'products_ranking'
  end
end

app/models/product_decorator.rb
Spree::Product.class_eval do
  has_many :likes
  scope :likes_ranking, ->{ joins(:likes).order('likes_count DESC') }

  def liked_by?(user)
    likes.exists?(user: user)
  end
end

app/models/spree/like.rb
class Spree::Like < ActiveRecord::Base
  belongs_to :product, counter_cache: true
  belongs_to :user

  validates :user_id, uniqueness: { scope: :product_id }
end

app/models/user_decorator.rb
Spree::User.class_eval do
  has_many :likes

  def like(product)
    self.likes.create(product: product) unless likes.exists?(product: product)
  end
end

app/controllers/spree/admin/products_controller_decorator.rb
Spree::Admin::ProductsController.class_eval do
  def products_ranking
    @collection = Spree::Product.likes_ranking.page(params[:page])
  end
end

app/controllers/spree/likes_controller.rb
class Spree::LikesController < Spree::StoreController
  rescue_from ActiveRecord::RecordNotFound, :with => :render_404
  helper 'spree/products'
  def like_product
    current_spree_user.like(product)
    redirect_to product
  end

  def unlike_product
    product.likes.where(user: current_spree_user).destroy_all
    redirect_to product
  end

  def index
    @searcher = build_searcher(params)
    @products = @searcher.retrieve_products
    @products = @products.where(id: current_spree_user.likes.pluck(:product_id))
  end

  private

  def product
    @product ||= Spree::Product.find(params[:id])
  end
end

app/views/spree/admin/products/products_ranking.html.erb
<% content_for :page_title do %>
  <%= t('spree_product_like.admin.products_ranking_title') %>
<% end %>
<% if @collection.any? %>
  <%= paginate @collection %>
  <table class="index" id="listing_products">
    <colgroup>
      <col style="width: 60%;"/>
      <col style="width: 20%;"/>
    </colgroup>
    <thead>
      <tr data-hook="admin_products_pending_questions_headers">
        <th><%= Spree.t(:products) %></th>
        <th><%= t('admin.likes_count') %></th>
      </tr>
    </thead>
    <tbody>
      <% @collection.each do |product| %>
        <tr class="<%= cycle('odd', 'even') %>">
          <td>
            <%= link_to product.name, edit_admin_product_path(product) %>
          </td>
          <td>
            <%= product.likes_count %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @collection %>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= t('admin.no_liked_products') %>
  </div>
<% end %>

app/views/spree/likes/index.html.erb
<% content_for :sidebar do %>
  <div data-hook="homepage_sidebar_navigation">
    <%= render :partial => 'spree/shared/taxonomies' %>
  </div>
<% end %>

<div data-hook="search_results">
  <% if @products.empty? %>
    <h6 class="search-results-title"><%= Spree.t(:no_products_found) %></h6>
<% else %>
    <%= render :partial => 'spree/shared/products', :locals => { :products => @products } %>
<% end %>
</div>

app/views/spree/products/_like.html.erb
<% if current_spree_user.present? %>
  <div class="product-likes" data-hook="product-likes">

  <% if current_spree_user.admin? %>
    <%= pluralize(@product.likes_count, t('spree_product_like.likes.like')) %>

  <% else %>
    <% if @product.liked_by?(current_spree_user) %>
      <div data-hook="product-dislike-button">
        <%= button_to @product.likes_count, unlike_product_path(id: @product.id), id: 'like-button', class: 'button dislike', title: t('spree_product_like.likes.unlike'), type: :submit, method: :delete %>
      </div>
    <% else %>
      <div data-hook="product-like-button">
        <%= button_to @product.likes_count, like_product_path(id: @product.id), id: 'like-button', class: 'button like', title: t('spree_product_like.likes.like'), type: :submit %>
      </div>
    <% end %>
  <% end %>

  </div>
<% end %>